config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)",locale: /#{I18n.available_locales.join("|")}/ do
    get 'userexecutors/show'
    get 'usercustomers/show'


    get 'checkout', to: 'checkouts#show'
    get 'checkout/success', to: 'checkouts#success'
    get 'billing', to: 'billing#show'

    resources :rooms do
    resources :messages
    end

    devise_for :usercustomers
    # devise_for :userexecutors

    devise_for :userexecutors, controllers:{
    sessions: 'userexecutors/sessions',
    registrations: 'userexecutors/registrations'
    }

    root 'open#after_registrationexe'



    devise_scope :usercustomer do
    get 'usercustomers',to: 'devise/sessions#new'
    end


    # resources :open




    # get '/userexecutors/default_profile.jpg'
    get 'open/page1'
    get 'open/page2'
    get 'open/pageinreg1', as: 'cus'
    get 'open/pageinreg2', as: 'exe'
    get 'open/after_registrationcus',to:"open#after_registrationcus", as: 'afteregcus'
    get 'open/after_registrationexe',to:"open#after_registrationexe", as: 'afteregexe'
    get 'open/addinfocus' ,to:"open#addinfocus", as: 'addcusinfo'
    get '/addinfocus', to: "open#addinfocus" 
    get 'open/addinfoexe' ,to:"open#addinfoexe", as: 'addexeinfo'
    get '/addinfoexe', to: "open#addinfoexe" 
    get 'open/addexecutorreq' ,to:"open#addexecutorreq", as: 'addexereq'
    get '/addexecutorreq', to: "open#addexecutorreq" 

    get 'userexecutor/:id', to: 'userexecutors#show', as: 'userexecutor'
    get 'usercustomer/:id', to: 'usercustomers#show', as: 'usercustomer'
  end
end

app/controllers/open_controller.rb
class OpenController < ApplicationController
  before_action :authenticate_userexecutor!
  before_action :addinfocus, only: [:edit, :update]


 def show
  @userscus = Usercustomer.all
  @usersexe1 = Userexecutor.all
  # @usersexe11 = Usercustomer.find(params[:id])
  @one = params[:one]
 end

  def after_registrationexe
      @userscus = Usercustomer.all
      @usersexe1 = Userexecutor.all
      @users = Userexecutor.all_except(current_userexecutor).search(params)
      @users2 = Userexecutor.all_except(current_userexecutor).search2(params)
      @users3 = Userexecutor.all_except(current_userexecutor).search3(params)
      @users4 = Userexecutor.all_except(current_userexecutor).search4(params)
      @one = params[:one]
      # @usersexe11 = Usercustomer.find(params[:one])
  end
  
  def after_registrationcus
      @usersexe = Userexecutor.all
      @userscus1 = Usercustomer.all
  end
  
  def addinfocus
    @userscusinfofullname = Usercustomer.find_by(email: current_usercustomer.email)
    @userscusinfofullname.update(full_name: params[:name1])

    @userscusinfoinn = Usercustomer.find_by(email: current_usercustomer.email)
    @userscusinfoinn.update(inn: params[:inn1])

    @userscusinfonumber = Usercustomer.find_by(email: current_usercustomer.email)
    @userscusinfonumber.update(number: params[:number1])

    @userscusinfowebsite = Usercustomer.find_by(email: current_usercustomer.email)
    @userscusinfowebsite.update(website: params[:website1])
  end


  def addinfoexe
    @usersexeinfofullname = Userexecutor.find_by(email: current_userexecutor.email)
    @usersexeinfofullname.update(full_name: params[:name1])

    @usersexeinfoinn = Userexecutor.find_by(email: current_userexecutor.email)
    @usersexeinfoinn.update(inn: params[:inn1])

    @usersexeinfonumber = Userexecutor.find_by(email: current_userexecutor.email)
    @usersexeinfonumber.update(number: params[:number1])

    @usersexeinfowebsite = Userexecutor.find_by(email: current_userexecutor.email)
    @usersexeinfowebsite.update(website: params[:website1])
      
    @usersexeinforole = Userexecutor.find_by(email: current_userexecutor.email)
    @usersexeinforole.update(role: params[:role1])

  end




  def addexecutorreq
    # @arrdate = Array.new
    # @perem = current_userexecutor.free_date
    # @arrdate.push(@perem.to_s)
    # @startdd = params[:date1]
    # @arrdate.push(@startdd)


    @usersexeinfodate = Userexecutor.find_by(email: current_userexecutor.email)
    # @usersexeinfodate.update(free_date: (@arrdate).map{|date| date.to_s})
    @usersexeinfodate.update(free_date: params[:date1])


    @usersexeinfofee = Userexecutor.find_by(email: current_userexecutor.email)
    @usersexeinfofee.update(fee: params[:fee1])

    @usersexeinfofee = Userexecutor.find_by(email: current_userexecutor.email)
    @usersexeinfofee.update(category: params[:category1])
      
  end

  



end

app/views/open/_contact.html.erb
<tr id="<%= dom_id(contact) %>" data-stream-enter-class="animate-item-in" data-stream-exit-class="animate-item-out">
  <td><%= link_to contact.full_name, userexecutor_path(contact), data: { turbo_frame: "_top" } %></td>
  <td><%= contact.inn %></td>
  <td><%= contact.email %></td>
</tr>

app/views/open/_contact2.html.erb
<tr id="<%= dom_id(contact2) %>" data-stream-enter-class="animate-item-in" data-stream-exit-class="animate-item-out">
  <td><%= link_to contact2.full_name, userexecutor_path(contact2), data: { turbo_frame: "_top" } %></td>
  <td><%= contact2.inn %></td>
  <td><%= contact2.email %></td>
</tr>

app/views/open/_contact3.html.erb
<tr id="<%= dom_id(contact3) %>" data-stream-enter-class="animate-item-in" data-stream-exit-class="animate-item-out">
  <td><%= contact3.id %></td>
  <td><%= link_to contact3.full_name, userexecutor_path(contact3), data: { turbo_frame: "_top" } %></td>
  <td><%= contact3.inn %></td>
  <td><%= contact3.email %></td>
  <td><%= button_to "Delete", userexecutor_path(contact3), method: :delete, class: "btn btn-link btn-sm" %></td>
</tr>

app/views/open/_list.html.erb
    <style>



    </style>

<table class="table table-zebra mt-0 w-full">
  <thead>
    <tr class="w-full">
      <th class="text-left"><%=t('Name')%></th>
      <th class="text-left"><%=t('Inn')%></th>
      <th class="text-left"><%=t('Email')%></th>
    </tr>
  </thead>
  <tbody id="contacts-list" data-controller="contacts" data-action="">
  <% contacts.each do |contact| %>
    <%= render partial: "contact", locals: { contact: contact }  %>
  <% end %>
  </tbody>
</table>
<div class="text-gray-400 mt-4 text-xs text-right" id="contacts-count">
</div>

app/views/open/_list2.html.erb
    <style>



    </style>

<table class="table table-zebra mt-0 w-full">
  <thead>
    <tr class="w-full2">
      <th class="text-left">Name</th>
      <th class="text-left">Inn</th>
      <th class="text-left">Email</th>
    </tr>
  </thead>
  <tbody id="contacts2-list" data-controller="contacts2" data-action="">
  <% contacts2.each do |contact2| %>
    <%= render partial: "contact2", locals: { contact2: contact2 }  %>
  <% end %>
  </tbody>
</table>
<div class="text-gray-400 mt-4 text-xs text-right" id="contacts2-count">
</div>

app/views/open/_list3.html.erb
    <style>



    </style>

<table class="table table-zebra mt-0 w-full">
  <thead>
    <tr class="w-full">
      <th class="text-left">ID</th>
      <th class="text-left">Name</th>
      <th class="text-left">Inn</th>
      <th class="text-left">Email</th>
      <th class="text-center" colspan="2">Actions</th>
    </tr>
  </thead>
  <tbody id="contacts-list" data-controller="contacts" data-action="">
  <% contacts3.each do |contact| %>
    <%= render partial: "contact", locals: { contact: contact }  %>
  <% end %>
  </tbody>
</table>
<div class="text-gray-400 mt-4 text-xs text-right" id="contacts-count">
</div>

app/views/open/addexecutorreq.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand"> Enter the nearest free date and fee</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Переключатель навигации">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%=afteregexe_path%>"> Return </a>
        </li>
      </ul>
    </div>
  </div>
</nav>


<%= form_with url: "/addexecutorreq", data: { behavior: "autosave" }, method: :get do |f1| %>
  <div class="form-group">
    <%= f1.label :date1 %><br />
    <%= f1.date_field :date1, class: "form-control" %>
  </div>


  <div class="form-group">
    <%= f1.label :fee1 %><br />
    <%= f1.number_field :fee1, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f1.label :category1 %><br />
    <%= f1.text_field :category1, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f1.submit "Add" , data: {turbo: false}, class:"btn btn-primary"%>
  </div>

<% end %>

app/views/open/addinfocus.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Add Customer info</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Переключатель навигации">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%=afteregcus_path%>"> Return </a>
        </li>
      </ul>
    </div>
  </div>
</nav>


<%= form_with url: "/addinfocus", data: { behavior: "autosave" }, method: :get do |f| %>

  <div class="form-group">
    <%= f.label :name1 %><br />
    <%= f.text_field :name1, autofocus: true, autocomplete: "name", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :inn1 %>
    <%= f.number_field :inn1, autocomplete: "inn", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :number1 %>
    <%= f.text_field :number1, autocomplete: "898185574454", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :website1 %><br />
    <%= f.text_field :website1, autocomplete: "www/leningrad", class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit "Add information" , data: {turbo: false}, class:"btn btn-primary"%>
  </div>
<% end %>

app/views/open/addinfoexe.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#"><%=t('Add Executor info')%></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Переключатель навигации">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%=afteregexe_path%>"> <%=t('Return')%> </a>
        </li>
      </ul>
    </div>
  </div>
</nav>


<%= form_with url: "/addinfoexe", data: { behavior: "autosave" }, method: :get do |f| %>

  <div class="form-group">
    <%= f.label t('open.addinfoexe.name1') %><br />
    <%= f.text_field :name1, autofocus: true, autocomplete: "name", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label t('open.addinfoexe.inn1') %>
    <%= f.number_field :inn1, autocomplete: "inn", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label t('open.addinfoexe.number1') %>
    <%= f.text_field :number1, autocomplete: "898185574454", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label t('open.addinfoexe.website1') %><br />
    <%= f.text_field :website1, autocomplete: "www/leningrad", class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit t("Add information") , data: {turbo: false}, class:"btn btn-primary"%>
  </div>


  <div>
    <%= label :role1, t("Customer"), value: false %>
    <%= f.radio_button :role1, false, :checked => true, :value => false %>
  </div>
  <div>
    <%= label :role1, t("Executor"), value: true %>
    <%= f.radio_button :role1, true, :value => true%>
  </div>

  
  
<% end %>

app/views/open/after_registrationcus.html.erb
<!DOCTYPE html>
<html>
  <head>
  </head>
  <body>

<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand">Customer</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Переключатель навигации">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%=addexereq_path%>"> Add requirement </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%=rooms_path%>">Chat </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">????????2</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Account
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="<%= destroy_usercustomer_session_path %>">Exit</a></li>
            <li><a class="dropdown-item" data-bs-toggle="modal" data-bs-target="#staticBackdrop">Contacts</a></li>
            <li><a class="dropdown-item" href="<%= addcusinfo_path %>">Add info about you</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>




<!-- Модальное окно -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">For questions and suggestions</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
      </div>
      <div class="modal-body">
        email:rusugarov@gmail.com
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>



<% k = 1 %>
<h3>View executor</h3>

<a id="MMM" data-bs-toggle="modal" data-bs-target="#staticBackdrop">Contacts</a>

  <table class = "table table-hover">
    <thead class ="thead-dark">
      <tr>
        <th>Number</th>
        <th>User</th>
        <th>full_name</th>
        <th>inn</th>
        <th>number</th>
        <th>website</th>
      </tr>
    </thead>

    <tbody>
    
    <% k = 1 %>
    <%@usersexe1.each do |user|%>
      <tr onclick="window.location.href = '<%= addexeinfo_path %>'; return false">
        <td><%= k %></td>
        <td><%= user.email %></td>
        <td><%= user.full_name %></td>
        <td><%= user.inn %></td>
        <td><%= user.number %></td>
        <td><%= user.website %></td>
      </tr>
      <% k += 1 %>
    <% end%>
    </tbody>
  </table>









  </body>
</html>

app/views/open/page1.html.erb
<head>
  <style>
    div.button
    {
      margin:0 auto;
      text-align:center;
    }
    
    h3.blocktext 
    {
    text-align:center;
    margin-top: 15%;
    margin-left: auto;
    margin-right: auto;
    width: 8em
    }
  </style>
</head>



<h3 class="blocktext">Who are you?</h3>

<%= form_with url: exe_path, method: :get do |form2| %>
  <div class="button">
    <%= form2.submit "EXECUTOR", class:"btn btn-primary" %>
  </div>
<% end %>

app/views/open/pageinreg1.html.erb
<head>
  <style>
    div.button
    {
      margin:0 auto;
      text-align:center;
    }
    
    h3.blocktext 
    {
    text-align:center;
    margin-top: 15%;
    margin-left: auto;
    margin-right: auto;
    width: 13em
    }
  </style>
</head>



<h3 class="blocktext">What do you want?</h3>
<%= form_with url: new_usercustomer_session_path, method: :get do |form1| %>
  <div class="button">
    <%= form1.submit "SIGN IN", class:"btn btn-primary" %>
  </div>
<% end %>
<%= form_with url: new_usercustomer_registration_path, method: :get do |form2| %>
  <div class="button">
    <%= form2.submit "REGISTRATION", class:"btn btn-primary" %>
  </div>
<% end %>

app/views/open/pageinreg2.html.erb
<head>
  <style>
    div.button
    {
      margin:0 auto;
      text-align:center;
    }
    
    h3.blocktext 
    {
    text-align:center;
    margin-top: 15%;
    margin-left: auto;
    margin-right: auto;
    width: 13em
    }
  </style>
</head>



<h3 class="blocktext">What do you want?</h3>
<%= form_with url: new_userexecutor_session_path, method: :get do |form1| %>
  <div class="button">
    <%= form1.submit "SIGN IN", class:"btn btn-primary" %>
  </div>
<% end %>
<%= form_with url: new_userexecutor_registration_path, method: :get do |form2| %>
  <div class="button">
    <%= form2.submit "REGISTRATION", class:"btn btn-primary" %>
  </div>
<% end %>