config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)",locale: /#{I18n.available_locales.join("|")}/ do
    get 'userexecutors/show'
    get 'usercustomers/show'


    get 'checkout', to: 'checkouts#show'
    get 'checkout/success', to: 'checkouts#success'
    get 'billing', to: 'billing#show'

    resources :rooms do
    resources :messages
    end

    devise_for :usercustomers
    # devise_for :userexecutors

    devise_for :userexecutors, controllers:{
    sessions: 'userexecutors/sessions',
    registrations: 'userexecutors/registrations'
    }

    root 'open#after_registrationexe'



    devise_scope :usercustomer do
    get 'usercustomers',to: 'devise/sessions#new'
    end


    # resources :open




    # get '/userexecutors/default_profile.jpg'
    get 'open/page1'
    get 'open/page2'
    get 'open/pageinreg1', as: 'cus'
    get 'open/pageinreg2', as: 'exe'
    get 'open/after_registrationcus',to:"open#after_registrationcus", as: 'afteregcus'
    get 'open/after_registrationexe',to:"open#after_registrationexe", as: 'afteregexe'
    get 'open/addinfocus' ,to:"open#addinfocus", as: 'addcusinfo'
    get '/addinfocus', to: "open#addinfocus" 
    get 'open/addinfoexe' ,to:"open#addinfoexe", as: 'addexeinfo'
    get '/addinfoexe', to: "open#addinfoexe" 
    get 'open/addexecutorreq' ,to:"open#addexecutorreq", as: 'addexereq'
    get '/addexecutorreq', to: "open#addexecutorreq" 

    get 'userexecutor/:id', to: 'userexecutors#show', as: 'userexecutor'
    get 'usercustomer/:id', to: 'usercustomers#show', as: 'usercustomer'
  end
end

app/models/room.rb
class Room < ApplicationRecord
    validates_uniqueness_of :name
    scope :public_rooms, -> {where(is_private: false)}
    after_create_commit {broadcast_if_public }
    has_many :messages
    has_many :participants, dependent: :destroy

    def broadcast_if_public
        broadcast_append_to "rooms" unless self.is_private
    end

    def self.create_private_room(userexecutors,room_name)
        single_room = Room.create(name: room_name, is_private: true)
            userexecutors.each do |userexecutor|
                Participant.create(userexecutor_id: userexecutor.id, room_id:single_room.id)
            end
        single_room
    end

    def participant?(room, userexecutor)
        room.participants.where(userexecutor: userexecutor).exists?
        Participant.where(userexecutor_id: userexecutor.id, room_id: room.id).exists?
      end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  # before_action :authenticate_userexecutor!
  def index
    @room = Room.new
    @rooms = Room.public_rooms

    @userexecutors = Userexecutor.all_except(current_userexecutor)
    @userexecutors = Userexecutor.all_except(current_userexecutor)
    @userexecutorse = Userexecutor.where(role: 'true')
    @userexecutorsc = Userexecutor.where(role: 'false')

    
    @usercustomers = Usercustomer.all_except(current_usercustomer)

    render 'index'
  end

  def show
    @single_room = Room.find(params[:id])

    @room = Room.new
    @rooms = Room.public_rooms

    @message = Message.new
    @messages = @single_room.messages.order(created_at: :asc)

    @userexecutors = Userexecutor.all_except(current_userexecutor)
    @usercustomers = Usercustomer.all_except(current_usercustomer)
    @userexecutorse = Userexecutor.where(role: 'true')
    @userexecutorsc = Userexecutor.where(role: 'false')
    
    render 'index'
  end

  def create
    @room = Room.create(name: params['room']['name'])
  end
  
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_room.html.erb
<div>
    <%= link_to room.name, room, data: {turbo: "false"}%>
</div>

app/views/rooms/index.html.erb
<% if userexecutor_signed_in?%>
  <div id='chatroom_container' class="row bg-dark text-light">
    <div id='side_panel' class='col-md-4 col-sm-4'>
      <li class="nav-item">
      <%= link_to t("Return"), afteregexe_path, class: "nav-link" %>
      </li>
      <h5><%=current_userexecutor.email%></h5>
      <h4><%=t('User')%></h4>
      <%= turbo_stream_from 'userexecutors' %>
      <div id='userexecutors'>


        <%if current_userexecutor.role == false %>
          <%@userexecutors.each do |user|%>
            <%if user.role == true %>
              <%=render user%>
            <%end%>
          <%end%>
        <%else%>
          <%@userexecutors.each do |user|%>
            <%if user.role == false %>
              <%=render user%>
            <%end%>
          <%end%>
        <%end%>


        </div>
      </div>
      <div id='room_container'
class ='col-md-8 col-sm-8 bg-dark text-light'>
        <% if @single_room%>
          <div id='single_room'>
            <h4 class='text-center'><%=@userexecutor&.email || @single_room.name %></h4>
            <%= turbo_stream_from @single_room%>
            <div id='messages' data-controller='scroll'>
              <%= render @messages%>
            </div>
            <%=render 'layouts/new_message_form'%>
          </div>
        <%end%>
      </div>
    <%else%>
      <div id='chatroom_container' class="row bg-dark text-light">
        <div id='side_panel' class='col-md-4 col-sm-4'>
          <h5><%=current_usercustomer.email%></h5>
          <h4><%=t('User')%></h4>
          <%= turbo_stream_from 'usercustomers' %>
          <div id='usercustomers'>
            <%=render @usercustomers%>
          </div>
        </div>
        <div id='room_container'
class ='col-md-8 col-sm-8 bg-dark text-light'>
          <% if @single_room%>
            <div id='single_room'>
              <h4 class='text-center'><%=@usercustomer&.email || @single_room.name %></h4>
              <%= turbo_stream_from @single_room%>
              <div id='messages' data-controller='scroll'>
                <%= render @messages%>
              </div>
              <%=render 'layouts/new_message_form'%>
            </div>
          <%end%>
        </div>
      <%end%>