config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)",locale: /#{I18n.available_locales.join("|")}/ do
    get 'userexecutors/show'
    get 'usercustomers/show'


    get 'checkout', to: 'checkouts#show'
    get 'checkout/success', to: 'checkouts#success'
    get 'billing', to: 'billing#show'

    resources :rooms do
    resources :messages
    end

    devise_for :usercustomers
    # devise_for :userexecutors

    devise_for :userexecutors, controllers:{
    sessions: 'userexecutors/sessions',
    registrations: 'userexecutors/registrations'
    }

    root 'open#after_registrationexe'



    devise_scope :usercustomer do
    get 'usercustomers',to: 'devise/sessions#new'
    end


    # resources :open




    # get '/userexecutors/default_profile.jpg'
    get 'open/page1'
    get 'open/page2'
    get 'open/pageinreg1', as: 'cus'
    get 'open/pageinreg2', as: 'exe'
    get 'open/after_registrationcus',to:"open#after_registrationcus", as: 'afteregcus'
    get 'open/after_registrationexe',to:"open#after_registrationexe", as: 'afteregexe'
    get 'open/addinfocus' ,to:"open#addinfocus", as: 'addcusinfo'
    get '/addinfocus', to: "open#addinfocus" 
    get 'open/addinfoexe' ,to:"open#addinfoexe", as: 'addexeinfo'
    get '/addinfoexe', to: "open#addinfoexe" 
    get 'open/addexecutorreq' ,to:"open#addexecutorreq", as: 'addexereq'
    get '/addexecutorreq', to: "open#addexecutorreq" 

    get 'userexecutor/:id', to: 'userexecutors#show', as: 'userexecutor'
    get 'usercustomer/:id', to: 'usercustomers#show', as: 'usercustomer'
  end
end

app/views/layouts/_new_message_form.html.erb
<div class = 'form-group msg-form'>
<%= form_with(model:[@single_room,@message],remote: true, class:'d-flex', data:{controller: "reset-form", action: "turbo:submit-end->reset-form#reset"}) do |f|%>
    <%= f.text_field :body, id: 'chat-text', class: 'form-control msg-content', autocomplete: 'off' %>
    <%= f.submit data: {disable_with: false},class: 'btn btn-primary' %>
</div>
<%end%>

app/views/layouts/_new_room_form.html.erb
<%= form_with(model: @room, remote: true, calss:'d-flex'), data:{controller: "reset-form", action: "turbo:submit-end->reset-form#reset"}) do |f|%>
    <%= f.text_field :name, class: 'form-control', autocomplete: 'off'%>
    <%= f.submit data: {disable_with:false}%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ZACH</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-uWxY/CJNBR+1zjPWmfnSnVxwRheevXITnMqoEIeG1LJrdI0GlVs/9cVSyPYXdcSF" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ" crossorigin="anonymous"></script>
    
    <style>
      <%= ".msg-#{current_userexecutor&.id}"%>{
        background-color:#007bff !important;
        padding: 10px;
      }
      <%= ".cont-#{current_userexecutor&.id}"%>{
        display:flex;
        justify-content:flex-end;
      }

      body
      {
        background:"Zach/app/assets/images/default_profile.jpg";
      }

      #footer
      {
        position: fixed;
        left: 45%;
        font-family: cursive;
        bottom: 0;
        padding: 10px;
      }

    
    </style>

    <script src="https://js.stripe.com/v3"></script>
 
   </head>
  <body>





  <div id = "footer"> Prod.by Dr Dre </div>


    <% flash.each do |name, message| %>
      <div class="alert <%= bootstrap_class_for(name)%>">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Закрыть"></button>
        <%= message %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>